modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "multiblocklib"
version = "${version}"
displayName = "MultiblockLib"
authors = "Kehrweek, Quinntyx, and KiraCoding"
description = '''
A library to abstract data-driven multiblock structures for developers.
'''
#logoFile = ""

[[dependencies.multiblocklib]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiblocklib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiblocklib]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"
